server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: UNGebw86BmF4ZlTBvIvhyCO9YDHUbYEb
            client-secret: bHlzO16P0XUNDpg5iSjjs0sRdfLfB0dMGGfcZAHkQDYB3hwvsu7rAfxNgjudZzGI
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://sample-auth0-ruuu.jp.auth0.com/
